var annotated =
[
    [ "anonymous_namespace{cpu_find_discreet_objects_pass.cpp}", "namespaceanonymous__namespace_02cpu__find__discreet__objects__pass_8cpp_03.html", null ],
    [ "anonymous_namespace{video_producer.cpp}", "namespaceanonymous__namespace_02video__producer_8cpp_03.html", null ],
    [ "flitr", "namespaceflitr.html", "namespaceflitr" ],
    [ "_DS_MEDIA_FORMAT", "struct___d_s___m_e_d_i_a___f_o_r_m_a_t.html", "struct___d_s___m_e_d_i_a___f_o_r_m_a_t" ],
    [ "BackgroundTriggerThread", "class_background_trigger_thread.html", "class_background_trigger_thread" ],
    [ "CAutoLock", "class_c_auto_lock.html", "class_c_auto_lock" ],
    [ "CPUAVRGIMG_Shader", "class_c_p_u_a_v_r_g_i_m_g___shader.html", "class_c_p_u_a_v_r_g_i_m_g___shader" ],
    [ "CPUGAUSFILT_Shader", "class_c_p_u_g_a_u_s_f_i_l_t___shader.html", "class_c_p_u_g_a_u_s_f_i_l_t___shader" ],
    [ "CPUSUM_Shader", "class_c_p_u_s_u_m___shader.html", "class_c_p_u_s_u_m___shader" ],
    [ "DSVL_GraphManager", "class_d_s_v_l___graph_manager.html", "class_d_s_v_l___graph_manager" ],
    [ "DSVL_VideoSource", "class_d_s_v_l___video_source.html", "class_d_s_v_l___video_source" ],
    [ "GLSLKeepHistoryPass", "class_g_l_s_l_keep_history_pass.html", "class_g_l_s_l_keep_history_pass" ],
    [ "KeyPressedHandler", "class_key_pressed_handler.html", "class_key_pressed_handler" ],
    [ "MemoryBufferEntry", "struct_memory_buffer_entry.html", "struct_memory_buffer_entry" ],
    [ "MemoryBufferHandle", "struct_memory_buffer_handle.html", "struct_memory_buffer_handle" ],
    [ "NullStreamBuffer", "class_null_stream_buffer.html", "class_null_stream_buffer" ],
    [ "PickHandler", "class_pick_handler.html", "class_pick_handler" ],
    [ "pitched_2d_range", "classpitched__2d__range.html", "classpitched__2d__range" ],
    [ "PostRenderCallback", "class_post_render_callback.html", "class_post_render_callback" ],
    [ "PreRenderCallback", "class_pre_render_callback.html", "class_pre_render_callback" ],
    [ "SimpleShaderPass", "class_simple_shader_pass.html", "class_simple_shader_pass" ],
    [ "TestConsumer", "class_test_consumer.html", "class_test_consumer" ],
    [ "TestProducer", "class_test_producer.html", "class_test_producer" ]
];